### ISSUE TITLE
Can't install (No package 'sdl2' found)

### ISSUE THREAD

**Issue by mhausenblas** [rbaron/awesomenes#2]
Tried to `go get` it with Go 1.10:

```
$ go get github.com/rbaron/awesomenes
# pkg-config --cflags sdl2
Package sdl2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl2' found
pkg-config: exit status 1
```

Any idea?

BTW, awesome job, really would love to use it :)

**Comment by rbaron** [comment]
Hi @mhausenblas. My bad, I forgot to document this. On my MacOS, I had to install `sdl2`. Using homebrew I did:

```
$ brew install sdl2
```

You probably need to do the same on your system. Which OS are you using?

**Comment by mhausenblas** [comment]
Awesome, thanks @rbaron that did the trick. Yes macOS here as well …
